package com.nttdata.de.sky.connector.faamockup;

import com.nttdata.de.lib.logging.SkyLogger;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.1 2013-11-25T16:48:07.506+01:00 Generated source version: 2.5.1
 */

public class MockFAAStaticServiceProvider extends Thread {
	public static String address = "http://localhost:9300/BusinessService/CustomerServiceFAA";
	public static String setupScript = null;
	public static String dataScript = null;
	public static String cleanupScript = null;

	private MockFaaStaticPortTypeImpl implementor;
	private Endpoint e;
	private Boolean init = true;

	public MockFAAStaticServiceProvider() {
		super();
	}
	
	public MockFAAStaticServiceProvider(Boolean init) {
		this.init = init;
	}

	public static void main(String args[]) throws java.lang.Exception {
		if (args.length > 0)
			MockFAAStaticServiceProvider.address = args[0];
		if (args.length > 1)
			MockFAAStaticServiceProvider.setupScript = args[1];
		if (args.length > 2)
			MockFAAStaticServiceProvider.dataScript = args[2];

		new MockFAAStaticServiceProvider().start();
	}

	public void run() {
		SkyLogger.getMediatrixLogger().info("Starting Provider at " + address);
		implementor = new MockFaaStaticPortTypeImpl();
		e = Endpoint.publish(address, implementor);
	}

	public void shutdown() {
	//	implementor.cleanupDatabase(cleanupScript);
		if (e != null)
			e.stop();
	}
}
