package com.nttdata.de.sky.connector.faamockup;

import com.nttdata.de.lib.logging.SkyLogger;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.5.1 2013-11-25T16:48:07.506+01:00 Generated source version: 2.5.1
 */

public class MockFAADynamicServiceProvider extends Thread {
	public static String address = "http://localhost:9300/BusinessService/CustomerServiceFAA";
	public static String setupScript = null;
	public static String dataScript = null;
	public static String cleanupScript = null;

	private MockFaaDynamicPortTypeImpl implementor;
	private Endpoint e;
	private Boolean init = true;

	public MockFAADynamicServiceProvider() {
		super();
	}

	public MockFAADynamicServiceProvider(Boolean init) {
		this.init = init;
	}

	public static void main(String args[]) throws Exception {
		if (args.length > 0)
			MockFAADynamicServiceProvider.address = args[0];
		if (args.length > 1)
			MockFAADynamicServiceProvider.setupScript = args[1];
		if (args.length > 2)
			MockFAADynamicServiceProvider.dataScript = args[2];

		new MockFAADynamicServiceProvider().start();
	}

	public void run() {
		SkyLogger.getMediatrixLogger().info("Starting Provider at " + address);
		if (init) {
			implementor = new MockFaaDynamicPortTypeImpl(setupScript, dataScript);
		} else {
			implementor = new MockFaaDynamicPortTypeImpl(init);
		}
		e = Endpoint.publish(address, implementor);
	}

	public void shutdown() {
	//	implementor.cleanupDatabase(cleanupScript);
		if (e != null)
			e.stop();
	}
}
