package com.nttdata.de.sky.ityx.common;

/**
 * Defines server actions.
 *
 * @author DHIFLM
 *
 */
public enum Actions {
	ACTION_CANCELLATION,ACTION_OPENCANCELLATIONACTION, ACTION_FUZZY_SEARCH, ACTION_ARCHIVE_WRITE,ACTION_QUESTIONARCHIVE_WRITE,  ACTION_ARCHIVE_NEEDED, ACTION_ARCHIVE_POSSIBLE,QUESTIONSEND, ANSWERSEND, ACTION_REINDEX, ACTION_MX_RESOLVE, ACTION_GET_REASONS,ACTION_CREATE_DOCUMENT_ID, ACTION_LOAD_CUSTOMER, ACTION_LOAD_CUSTOMER_BYEMAIL, ACTION_LOAD_TEXTOBJECT, ACTION_LOAD_KEYWORD, ACTION_GETPROJECTINFO, ACTION_SBSINDEX, ACTION_UPDATELOG
}
