CREATE OR REPLACE FORCE VIEW "ITYX_CX"."NEWDB_FLAT_ALL" ("CUSTOMER_ID", "CONTRACT_ID", "HOUSE_NUMBER", "STREET", "ZIPCODE", "CITY", "ACCOUNT_NUMBER", "BANK_CODE", "BANK_ACCOUNT_HOLDER", "MOBILE_NUMBER", "EMAIL_ADDRESS", "FIRST_NAME", "LAST_NAME", "TELEPHONE_NUMBER", "SERIAL_NUMBER")
AS
  SELECT a.CUSTOMER_ID,
    b.CONTRACT_ID,
    b.HOUSE_NUMBER,
    b.STREET,
    b.ZIPCODE,
    b.CITY,
    b.ACCOUNT_NUMBER,
    b.BANK_CODE,
    b.BANK_ACCOUNT_HOLDER,
    a.MOBILE_NUMBER,
    a.EMAIL_ADDRESS,
    a.FIRST_NAME,
    a.LAST_NAME,
    a.TELEPHONE_NUMBER,
    c.SERIAL_NUMBER
  FROM (NEWDB_CUSTOMER_ALL a
  LEFT JOIN NEWDB_ASSET_ALL c
  ON c.CUSTOMER_ID=a.CUSTOMER_ID)
  LEFT JOIN NEWDB_CONTRACT_ALL b
  ON b.CUSTOMER_ID=a.CUSTOMER_ID;