/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.nttdata.de.sky.connector.newdbmockup;

import de.sky.integration.web.customerdataservice._1.*;

/**
 * This class was generated by Apache CXF 2.4.3 2011-10-25T09:14:10.298+02:00
 * Generated source version: 2.4.3
 * <p>
 * This implementation has been changed to build up a simple in-memory database
 * that can be used for unit tests.
 */

@javax.jws.WebService(serviceName = "CustomerDataService",
        portName = "CustomerDataServiceEndpoint",
        targetNamespace = "http://www.sky.de/integration/web/CustomerDataService/1.0",
        wsdlLocation = "CustomerDataService_mock.wsdl",
        endpointInterface = "de.sky.integration.web.customerdataservice._1.PortType")
public class MockNewDBStaticPortTypeImpl implements PortType {

    /*
     * (non-Javadoc)
     *
     * @see de.sky.integration.web.customerdataservice._1_0.PortType#
     * getDynamicCustomerData(de.sky.integration.web.customerdataservice._1.
     * GetDynamicCustomerDataRequestType getDynamicCustomerDataRequest )*
     */
    public GetDynamicCustomerDataResponseType getDynamicCustomerData(GetDynamicCustomerDataRequestType req) {
        de.sky.integration.web.customerdataservice._1.GetDynamicCustomerDataResponseType _return = new GetDynamicCustomerDataResponseType();
        _return.setCustomerId(req.getCustomerId());
        _return.setCustomer(new CustomerType());

        final CustomerType customer = _return.getCustomer();
        customer.setEmailAddress("mockup@customersky.de");
        customer.setFirstName("Mandel");
        customer.setLastName("Luigi");
        customer.setMobileNumber("+49 123 123123123");
        customer.setTelephoneNumber("+49 124 123123123");
        customer.setStamp("01.01.16");

/*        CampaignType campaignType = new CampaignType();
        campaignType.setCampaignType(rs.getString("CAMPAIGN_TYPE"));
        customer.getCampaign().add(campaignType);*/

        ContractType ctrType = new ContractType();
        ctrType.setAccountNumber("1234567");
        ctrType.setBankAccountHolder("Mockup Luigi");
        ctrType.setBankCode("54354322");
        ctrType.setCity("Vienna");
        ctrType.setHouseNumber("7");
        ctrType.setStreet("Strudelweg");
        ctrType.setZipCode("12345");
        if (req.getContractId()==null || req.getContractId().isEmpty() || req.getContractId().equals("0")) {
            ctrType.setContractId("54321");
        }else{
            ctrType.setContractId(req.getContractId());
        }

      //   ctrType.setWMFlag(rs.getString("WM_FLG"));

        // Sets mandate data.
       /* MandateType mandate = new MandateType();
        mandate.setMandateRefId(rs.getString("MANDATE_REF_ID"));
        mandate.setMandateStatus(rs.getString("MANDATE_STATUS"));
        mandate.setCustomerIBAN(rs.getString("CUSTOMER_IBAN"));
        mandate.setCustomerBIC(rs.getString("CUSTOMER_BIC"));
        ctrType.setMandate(mandate);*/

      /*  DunningType dt = new DunningType();
        dt.setDunningContractId(ctrType.getContractId());
        dt.setDunningLevel("0");
        customer.getDunning().add(dt);*/

        customer.getContract().add(ctrType);

        _return.setResult(ResultType.OK);
        _return.setRetCode("0");
        _return.setCustomerId(req.getCustomerId());

        return _return;
    }
}
