REMARK This script is executed and used for test cases only that employ the NewDBServiceProvider
REMARK This table should only be changed in conjuntion with customerdataserver.PortTypeImpl
REMARK Lines starting with REMARK indicate a comment and are ignored

CREATE TABLE NEWDB_CUSTOMER(
ROW_ID VARCHAR(15) NOT NULL,
CUSTOMER_ID VARCHAR(15),
MOBILE_NUMBER VARCHAR(15),
EMAIL_ADDRESS VARCHAR(50),
FIRST_NAME VARCHAR(100),
LAST_NAME VARCHAR(100),
TELEPHONE_NUMBER VARCHAR(40),
STATUS VARCHAR(30),
OPERATION_DATE DATE NOT NULL
);

CREATE TABLE NEWDB_CONTRACT(
CONTRACT_ID VARCHAR(30) NOT NULL,
CUSTOMER_ID VARCHAR(15),
HOUSE_NUMBER VARCHAR(30),
STREET VARCHAR(200),
ZIPCODE VARCHAR(30),
CITY VARCHAR(50),
COUNTRY VARCHAR(30),
ACCOUNT_NUMBER VARCHAR(50),
BANK_CODE VARCHAR(50),
BANK_ACCOUNT_HOLDER VARCHAR(50),
STATUS VARCHAR(30),
OPERATION_DATE DATE NOT NULL,
WM_FLG VARCHAR(1),
RECEPTION VARCHAR(50),
OPERATOR VARCHAR(50),
PLATFORM VARCHAR(50),
CONTRACT_TYPE VARCHAR(50),
RATECARD_FLG VARCHAR(2), 
MANDATE_REF_ID VARCHAR(50), 
MANDATE_STATUS VARCHAR(50), 
SIGNATURE_FLAG CHAR(1), 
SIGNATURE_DATE DATE, 
CUSTOMER_IBAN VARCHAR(50), 
CUSTOMER_BIC VARCHAR(50),
CONTRACT_DATE DATE
);

CREATE TABLE NEWDB_CAMPAIGN(
CUSTOMER_ID VARCHAR(15),
CAMPAIGN_ID VARCHAR(45),
OPERATION_DATE DATE NOT NULL,
SBLCUSTOMER_ID VARCHAR(15)
);

CREATE TABLE NEWDB_CAMPAIGN_CONF(
CAMPAIGN_ID VARCHAR(15) NOT NULL,
CAMPAIGN_TYPE VARCHAR(30),
STATUS VARCHAR(30),
START_DATE DATE,
END_DATE DATE,
OPERATION_DATE DATE NOT NULL
);

CREATE TABLE NEWDB_ASSET(
CUSTOMER_ID VARCHAR(15),
CONTRACT_ID VARCHAR(30),
SERIAL_NUMBER VARCHAR(100) NOT NULL,
STATUS VARCHAR(30),
OPERATION_DATE DATE NOT NULL,
CONTACT_INTERVAL_3D VARCHAR(2),
CONTACT_INTERVAL_7D VARCHAR(2),
CONTACT_INTERVAL_14D VARCHAR(2),
CONTACT_INTERVAL_21D VARCHAR(2),
CONTACT_INTERVAL_28D VARCHAR(2)
);
