
-- Erzeugt die Tabellen für die Simulation der NewDB-Tabellen
--------------------------------------------------------
--  DDL for Table NEWDB_CUSTOMER
--------------------------------------------------------

  CREATE TABLE "NEWDB_CUSTOMER" 
   (	"CUSTOMER_ID" VARCHAR2(15 BYTE), 
	"MOBILE_NUMBER" VARCHAR2(15 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(50 BYTE), 
	"FIRST_NAME" VARCHAR2(100 BYTE), 
	"LAST_NAME" VARCHAR2(100 BYTE), 
	"TELEPHONE_NUMBER" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"ROW_ID" VARCHAR2(15 BYTE),
	"OPERATION" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index NEWDB_CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEWDB_CUSTOMER_PK" ON "NEWDB_CUSTOMER" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table NEWDB_CUSTOMER
--------------------------------------------------------

  ALTER TABLE "NEWDB_CUSTOMER" ADD CONSTRAINT "NEWDB_CUSTOMER_PK" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "NEWDB_CUSTOMER" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Table NEWDB_CONTRACT
--------------------------------------------------------

  CREATE TABLE "NEWDB_CONTRACT" 
   (	"CUSTOMER_ID" VARCHAR2(15 BYTE), 
	"CONTRACT_ID" VARCHAR2(30 BYTE), 
	"HOUSE_NUMBER" VARCHAR2(30 BYTE), 
	"STREET" VARCHAR2(200 BYTE), 
	"ZIPCODE" VARCHAR2(30 BYTE), 
	"CITY" VARCHAR2(30 BYTE),
	"COUNTRY" VARCHAR2(30 BYTE),
	"ACCOUNT_NUMBER" VARCHAR2(50 BYTE), 
	"BANK_CODE" VARCHAR2(50 BYTE), 
	"BANK_ACCOUNT_HOLDER" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"OPERATION" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index NEWDB_CONTRACT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEWDB_CONTRACT_PK" ON "NEWDB_CONTRACT" ("CONTRACT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table NEWDB_CONTRACT
--------------------------------------------------------

  ALTER TABLE "NEWDB_CONTRACT" ADD CONSTRAINT "NEWDB_CONTRACT_PK" PRIMARY KEY ("CONTRACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "NEWDB_CONTRACT" MODIFY ("CONTRACT_ID" NOT NULL ENABLE);
  ALTER TABLE "NEWDB_CONTRACT" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table NEWDB_CONTRACT
--------------------------------------------------------

  ALTER TABLE "NEWDB_CONTRACT" ADD CONSTRAINT "NEWDB_CONTRACT_NEWDB_CUST_FK1" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "NEWDB_CUSTOMER" ("CUSTOMER_ID") ENABLE;




--------------------------------------------------------
--  DDL for Table NEWDB_ASSET
--------------------------------------------------------

  CREATE TABLE "NEWDB_ASSET" 
   (	"CONTRACT_ID" VARCHAR2(15 BYTE), 
	"SERIAL_NUMBER" VARCHAR2(100 BYTE), 
	"CUSTOMER_ID" VARCHAR2(15 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"OPERATION" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  DDL for Index NEWDB_ASSET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEWDB_ASSET_PK" ON "NEWDB_ASSET" ("SERIAL_NUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
--------------------------------------------------------
--  Constraints for Table NEWDB_ASSET
--------------------------------------------------------

  ALTER TABLE "NEWDB_ASSET" ADD CONSTRAINT "NEWDB_ASSET_PK" PRIMARY KEY ("SERIAL_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;
  ALTER TABLE "NEWDB_ASSET" MODIFY ("CONTRACT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table NEWDB_ASSET
--------------------------------------------------------

  ALTER TABLE "NEWDB_ASSET" ADD CONSTRAINT "NEWDB_ASSET_NEWDB_CONTRAC_FK1" FOREIGN KEY ("CONTRACT_ID")
	  REFERENCES "NEWDB_CONTRACT" ("CONTRACT_ID") DISABLE;
