-- Enfernt die FuzzyDB-Tabellen in der Contex-Datenbank

DROP TABLE "NEWDB_CUSTOMER_ALL" CASCADE CONSTRAINT;
DROP TABLE "NEWDB_CONTRACT_ALL" CASCADE CONSTRAINT;
DROP TABLE "NEWDB_ASSET_ALL" CASCADE CONSTRAINT;
DROP TABLE "NEWDB_ASSET_DELTA" CASCADE CONSTRAINT;