CREATE TABLE "ITYX_CX"."NEWDB_CUSTOMER_DELTA"
  (
    "CUSTOMER_ID"      VARCHAR2(15 BYTE),
    "MOBILE_NUMBER"    VARCHAR2(15 BYTE),
    "EMAIL_ADDRESS"    VARCHAR2(100 BYTE),
    "FIRST_NAME"       VARCHAR2(100 BYTE),
    "LAST_NAME"        VARCHAR2(100 BYTE),
    "TELEPHONE_NUMBER" VARCHAR2(40 BYTE),
    "STATUS"           VARCHAR2(30 BYTE),
    "ROW_ID"           VARCHAR2(15 CHAR),
    "OPERATION"        VARCHAR2(5 BYTE)
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "DATA" ;