CREATE TABLE "ITYX_CX"."NEWDB_CONTRACT_DELTA"
  (
    "CUSTOMER_ID"         VARCHAR2(15 BYTE),
    "CONTRACT_ID"         VARCHAR2(30 BYTE),
    "HOUSE_NUMBER"        VARCHAR2(30 BYTE),
    "STREET"              VARCHAR2(200 BYTE),
    "ZIPCODE"             VARCHAR2(30 BYTE),
    "CITY"                VARCHAR2(50 BYTE),
    "ACCOUNT_NUMBER"      VARCHAR2(50 BYTE),
    "BANK_CODE"           VARCHAR2(50 BYTE),
    "BANK_ACCOUNT_HOLDER" VARCHAR2(255 BYTE),
    "STATUS"              VARCHAR2(30 BYTE),
    "COUNTRY"             VARCHAR2(30 BYTE),
    "OPERATION"           VARCHAR2(5 BYTE)
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "DATA" ;