CREATE TABLE NEWDB_ASSET
  (
    CUSTOMER_ID    VARCHAR2(15 CHAR),
    CONTRACT_ID    VARCHAR2(30 CHAR),
    SERIAL_NUMBER  VARCHAR2(100 CHAR) NOT NULL ENABLE,
    STATUS         VARCHAR2(30 CHAR),
    OPERATION_DATE DATE NOT NULL ENABLE
  )
   TABLESPACE DATA ;
CREATE INDEX NEWDB_ASSETN_IND3 ON NEWDB_ASSET
  (
    SERIAL_NUMBER
  )
  TABLESPACE INDX ;
CREATE INDEX NEWDB_ASSETN_IND1 ON NEWDB_ASSET
  (
    CUSTOMER_ID
  )
  TABLESPACE INDX ;
CREATE INDEX NEWDB_ASSETN_IND2 ON NEWDB_ASSET
  (
    CONTRACT_ID ,
    SERIAL_NUMBER
  )
  TABLESPACE INDX ;
CREATE TABLE NEWDB_ASSET_STAGE
  (
    CUSTOMER_ID   VARCHAR2(15 CHAR),
    CONTRACT_ID   VARCHAR2(30 CHAR),
    SERIAL_NUMBER VARCHAR2(100 CHAR) NOT NULL ENABLE,
    STATUS        VARCHAR2(30 CHAR),
    OPERATION     CHAR(3 BYTE),
    OPERATION_DATE DATE NOT NULL ENABLE
  )
   TABLESPACE DATA ;
CREATE INDEX NEWDB_ASSET_STAGE_IND1 ON NEWDB_ASSET_STAGE
  (
    OPERATION_DATE
  )
  TABLESPACE DATA ;
CREATE TABLE NEWDB_CAMPAIGN
  (
    CUSTOMER_ID VARCHAR2(15 CHAR),
    CAMPAIGN_ID VARCHAR2(45 BYTE),
    OPERATION_DATE DATE NOT NULL ENABLE,
    SBLCUSTOMER_ID VARCHAR2(15 CHAR)
  )
   TABLESPACE DATA ;
CREATE INDEX NEWDBCAMPAIGN2N_IND3 ON NEWDB_CAMPAIGN
  (
    SBLCUSTOMER_ID ,
    CAMPAIGN_ID
  )
  TABLESPACE INDX ;
CREATE INDEX NEWDBCAMPN_IND1 ON NEWDB_CAMPAIGN
  (
    CUSTOMER_ID
  )
  TABLESPACE INDX ;
CREATE INDEX NEWDBCAMPN_IND2 ON NEWDB_CAMPAIGN
  (
    CAMPAIGN_ID
  )
  TABLESPACE INDX ;
CREATE TABLE NEWDB_CAMPAIGN_STAGE
  (
    CUSTOMER_ID VARCHAR2(15 CHAR),
    CAMPAIGN_ID VARCHAR2(45 BYTE),
    OPERATION   CHAR(1 CHAR) NOT NULL ENABLE,
    OPERATION_DATE DATE NOT NULL ENABLE
  )
   TABLESPACE DATA ;
CREATE INDEX NEWDB_CAMPAIGN_STAGE_IND1 ON NEWDB_CAMPAIGN_STAGE
  (
    OPERATION_DATE
  )
  TABLESPACE DATA ;
CREATE TABLE NEWDB_CAMPAIGN_CONF
  (
    CAMPAIGN_ID   VARCHAR2(15 CHAR) NOT NULL ENABLE,
    CAMPAIGN_TYPE VARCHAR2(30 CHAR),
    STATUS        VARCHAR2(30 CHAR),
    START_DATE DATE,
    END_DATE DATE,
    OPERATION_DATE DATE NOT NULL ENABLE
  )
   TABLESPACE DATA ;
CREATE INDEX NEWDBCAMPCONFN_IND1 ON NEWDB_CAMPAIGN_CONF
  (
    CAMPAIGN_ID
  )
  TABLESPACE INDX ;
CREATE TABLE NEWDB_CAMPAIGN_CONF_STAGE
  (
    CAMPAIGN_ID   VARCHAR2(15 CHAR) NOT NULL ENABLE,
    CAMPAIGN_TYPE VARCHAR2(30 CHAR),
    STATUS        VARCHAR2(30 CHAR),
    START_DATE DATE,
    END_DATE DATE,
    OPERATION CHAR(1 CHAR) NOT NULL ENABLE,
    OPERATION_DATE DATE NOT NULL ENABLE
  )
   TABLESPACE DATA ;
CREATE TABLE NEWDB_CONTRACT
  (
    CONTRACT_ID         VARCHAR2(30 CHAR) NOT NULL ENABLE,
    CUSTOMER_ID         VARCHAR2(15 CHAR),
    HOUSE_NUMBER        VARCHAR2(30 CHAR),
    STREET              VARCHAR2(200 CHAR),
    ZIPCODE             VARCHAR2(30 CHAR),
    CITY                VARCHAR2(50 CHAR),
    COUNTRY             VARCHAR2(30 CHAR),
    ACCOUNT_NUMBER      VARCHAR2(50 CHAR),
    BANK_CODE           VARCHAR2(50 CHAR),
    BANK_ACCOUNT_HOLDER VARCHAR2(50 CHAR),
    STATUS              VARCHAR2(30 CHAR),
    OPERATION_DATE		DATE NOT NULL ENABLE,
    WM_FLG				CHAR(1 CHAR),
  	RECEPTION			VARCHAR2(50 CHAR),
	OPERATOR			VARCHAR2(50 CHAR),
	PLATFORM			VARCHAR2(50 CHAR)
)
   TABLESPACE DATA ;
CREATE INDEX NEWDBCONTRACT2N_IND2 ON NEWDB_CONTRACT
  (
    CUSTOMER_ID ,
    CONTRACT_ID
  )
  TABLESPACE INDX ;
CREATE INDEX NEWDB_CONTRACTN_IND1 ON NEWDB_CONTRACT
  (
    CUSTOMER_ID
  )
  TABLESPACE INDX ;
CREATE INDEX NEWDB_CONTRACTN_IND2 ON NEWDB_CONTRACT
  (
    CONTRACT_ID
  )
  TABLESPACE INDX ;
CREATE TABLE NEWDB_CONTRACT_STAGE
  (
    CONTRACT_ID         VARCHAR2(30 CHAR) NOT NULL ENABLE,
    CUSTOMER_ID         VARCHAR2(15 CHAR),
    HOUSE_NUMBER        VARCHAR2(30 CHAR),
    STREET              VARCHAR2(200 CHAR),
    ZIPCODE             VARCHAR2(30 CHAR),
    CITY                VARCHAR2(50 CHAR),
    COUNTRY             VARCHAR2(30 CHAR),
    ACCOUNT_NUMBER      VARCHAR2(50 CHAR),
    BANK_CODE           VARCHAR2(50 CHAR),
    BANK_ACCOUNT_HOLDER VARCHAR2(50 CHAR),
    STATUS              VARCHAR2(30 CHAR),
    OPERATION           CHAR(3 BYTE) NOT NULL ENABLE,
    OPERATION_DATE		DATE NOT NULL ENABLE,
    WM_FLG				CHAR(1 CHAR),
  	RECEPTION			VARCHAR2(50 CHAR),
	OPERATOR			VARCHAR2(50 CHAR),
	PLATFORM			VARCHAR2(50 CHAR)
  )
   TABLESPACE DATA ;
CREATE INDEX NEWDB_CONTRACT_STAGE_IND1 ON NEWDB_CONTRACT_STAGE
  (
    OPERATION_DATE
  )
  TABLESPACE DATA ;
CREATE TABLE NEWDB_CUSTOMER
  (
    ROW_ID           VARCHAR2(15 CHAR) NOT NULL ENABLE,
    CUSTOMER_ID      VARCHAR2(15 CHAR),
    MOBILE_NUMBER    VARCHAR2(15 CHAR),
    EMAIL_ADDRESS    VARCHAR2(50 CHAR),
    FIRST_NAME       VARCHAR2(100 CHAR),
    LAST_NAME        VARCHAR2(100 CHAR),
    TELEPHONE_NUMBER VARCHAR2(40 CHAR),
    STATUS           VARCHAR2(30 CHAR),
    OPERATION_DATE	 DATE NOT NULL ENABLE
  )
   TABLESPACE DATA ;
CREATE INDEX NEWDBCUSTN_IND1 ON NEWDB_CUSTOMER
  (
    CUSTOMER_ID
  )
  TABLESPACE INDX ;
CREATE INDEX NEWDBCUSTOMER2N_IND2 ON NEWDB_CUSTOMER
  (
    CUSTOMER_ID ,
    ROW_ID
  )
  TABLESPACE INDX ;
CREATE TABLE NEWDB_CUSTOMER_STAGE
  (
    ROW_ID           VARCHAR2(15 CHAR) NOT NULL ENABLE,
    CUSTOMER_ID      VARCHAR2(15 CHAR),
    MOBILE_NUMBER    VARCHAR2(15 CHAR),
    EMAIL_ADDRESS    VARCHAR2(50 CHAR),
    FIRST_NAME       VARCHAR2(100 CHAR),
    LAST_NAME        VARCHAR2(100 CHAR),
    TELEPHONE_NUMBER VARCHAR2(40 CHAR),
    STATUS           VARCHAR2(30 CHAR),
    OPERATION        CHAR(3 BYTE) NOT NULL ENABLE,
    OPERATION_DATE DATE NOT NULL ENABLE
  )
   TABLESPACE DATA ;
  
  
CREATE OR REPLACE FORCE VIEW FUZZY_NEWDB
  (
    CUSTOMER_ID , CONTRACT_ID , HOUSE_NUMBER , STREET , ZIPCODE , CITY , ACCOUNT_NUMBER , BANK_CODE , BANK_ACCOUNT_HOLDER , MOBILE_NUMBER , EMAIL_ADDRESS , FIRST_NAME , LAST_NAME , TELEPHONE_NUMBER , SERIAL_NUMBER , WASH_MACHINE
  )
AS
  SELECT a.CUSTOMER_ID,
    b.CONTRACT_ID,
    b.HOUSE_NUMBER,
    b.STREET,
    b.ZIPCODE,
    b.CITY,
    b.ACCOUNT_NUMBER,
    b.BANK_CODE,
    b.BANK_ACCOUNT_HOLDER,
    a.MOBILE_NUMBER,
    a.EMAIL_ADDRESS,
    a.FIRST_NAME,
    a.LAST_NAME,
    a.TELEPHONE_NUMBER,
    c.SERIAL_NUMBER,
    b.WM_FLG WASH_MACHINE
  FROM (NEWDB_CUSTOMER a
  LEFT JOIN NEWDB_ASSET c
  ON c.CUSTOMER_ID=a.CUSTOMER_ID)
  LEFT JOIN NEWDB_CONTRACT b
  ON b.CUSTOMER_ID     =a.CUSTOMER_ID
  WHERE a.customer_id IS NOT NULL
  AND b.contract_id   IS NOT NULL
  AND b.customer_id   IS NOT NULL;
