CREATE TABLE "ITYX_CX"."NEWDB_ASSET_ALL"
  (
    "CONTRACT_ID"    VARCHAR2(30 BYTE),
    "SERIAL_NUMBER"  VARCHAR2(100 BYTE),
    "CUSTOMER_ID"    VARCHAR2(15 BYTE),
    "STATUS"         VARCHAR2(30 BYTE),
    "OPERATION"      VARCHAR2(5 BYTE),
    "OPERATION_DATE" VARCHAR2(20 BYTE)
  )
  SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "DATA" ;
CREATE INDEX "ITYX_CX"."INDEX3" ON "ITYX_CX"."NEWDB_ASSET_ALL"
  (
    "CONTRACT_ID",
    "SERIAL_NUMBER"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "INDX" ;
CREATE INDEX "ITYX_CX"."INDEX4" ON "ITYX_CX"."NEWDB_ASSET_ALL"
  (
    "CUSTOMER_ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "INDX" ;
CREATE INDEX "ITYX_CX"."INDEX5" ON "ITYX_CX"."NEWDB_ASSET_ALL"
  (
    "SERIAL_NUMBER"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS STORAGE
  (
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  TABLESPACE "INDX" ;