CREATE TABLE EBM_CONFIG
  (
    NAME         VARCHAR2(30 CHAR) NOT NULL ENABLE,
    VALUE_NUM    NUMBER(11,0),
    VALUE_STRING VARCHAR2(30 CHAR),
    UNITTYPE     VARCHAR2(30 CHAR) NOT NULL ENABLE,
    CONSTRAINT CEBM_CF_PK PRIMARY KEY (NAME)
  )
  TABLESPACE DWH_ETL_DATA ;
  DROP TABLE EBMD_EVENTGROUP_DSC;
CREATE TABLE EBMD_EVENTGROUP_DSC  (
    EVENTGROUP  VARCHAR2(50 CHAR),
    DESCRIPTION VARCHAR2(2000 CHAR),
    CONSTRAINT CEBMD_EG_PK PRIMARY KEY (EVENTGROUP) USING INDEX TABLESPACE DWH_ETL_INDEX 
  )
  TABLESPACE DWH_ETL_DATA;
CREATE TABLE EBMD_EVENT_DSC
  (
    EVENT       CHAR(2 CHAR),
    EVENTGROUP  VARCHAR2(25 CHAR),
    NAME        VARCHAR2(50 CHAR),
    DESCRIPTION VARCHAR2(4000 CHAR),
    CONSTRAINT CEBMD_ED_PK PRIMARY KEY (EVENT) USING INDEX TABLESPACE DWH_ETL_INDEX ENABLE,
    CONSTRAINT CEBMD_ED_FK_G FOREIGN KEY (EVENTGROUP) REFERENCES EBMD_EVENTGROUP_DSC(EVENTGROUP)
  )
  TABLESPACE DWH_ETL_DATA ;
CREATE TABLE EBMD_QTYPE_DESC
  (
    QTYPE       NUMBER,
    DESCRIPTION VARCHAR2(60 CHAR),
    CONSTRAINT CEBMD_FT_PK PRIMARY KEY (QTYPE)  USING INDEX TABLESPACE DWH_ETL_INDEX ENABLE
  )
  TABLESPACE DWH_ETL_DATA ;
CREATE TABLE EBMD_CHANNEL
  (
    CHANNEL     VARCHAR2(25 CHAR),
    DESCRIPTION VARCHAR2(255 CHAR),
    CONSTRAINT CEBMD_CHANNEL_PK PRIMARY KEY (CHANNEL)  USING INDEX TABLESPACE DWH_ETL_INDEX ENABLE
  )
  TABLESPACE DWH_ETL_DATA ;
CREATE TABLE EBMD_TENANT
  (
    TENANTID   NUMBER(11,0),
    TENANT     VARCHAR2(5 CHAR),
    TENANTNAME VARCHAR2(55 CHAR),
    CONSTRAINT CEBMD_TN_PK PRIMARY KEY (TENANTID)  USING INDEX TABLESPACE DWH_ETL_INDEX ENABLE
  )
  TABLESPACE DWH_ETL_DATA ;

--drop table EBMD_SUBPROJECT;
--alter table EBMD_SUBPROJECT add  (    MODIFIED      DATE);

CREATE TABLE EBMD_SUBPROJECT
  (
    SUBPROJECTID   NUMBER(11,0),
    TENANTID       NUMBER(11,0) NOT NULL ENABLE,
    SUBPROJECTNAME VARCHAR2(255 CHAR),
    CREATED        DATE,
    MODIFIED      DATE,
    DELETED        DATE,
    DELETIONFLAG   NUMBER(1),
    CONSTRAINT CEBMD_SP_PK PRIMARY KEY (SUBPROJECTID)  USING INDEX TABLESPACE DWH_ETL_INDEX ENABLE,
    CONSTRAINT CEBMD_SP_FK_TN FOREIGN KEY (TENANTID) REFERENCES EBMD_TENANT(TENANTID)
  )
  TABLESPACE DWH_ETL_DATA ;
  
--  Alter table EBMD_AGENCY add (    MODIFIED     DATE);
  
CREATE TABLE EBMD_AGENCY
  (
    AGENCYID     NUMBER(11,0),
    AGENCYNAME   VARCHAR2(30 CHAR),
    TENANTID     NUMBER(11,0) NOT NULL ENABLE,
    CREATED      DATE,
    MODIFIED     DATE,
    DELETED      DATE,
    DELETIONFLAG NUMBER(1),
    CONSTRAINT CEBMD_AG_PK PRIMARY KEY (AGENCYID)  USING INDEX TABLESPACE DWH_ETL_INDEX ENABLE,
    CONSTRAINT CEBMD_AG_FK_TN FOREIGN KEY (TENANTID) REFERENCES EBMD_TENANT(TENANTID)
  )
  TABLESPACE DWH_ETL_DATA ;
  drop table EBMD_KEYWORD;
  
--alter table   EBMD_KEYWORD add(   MODIFIED      DATE);
CREATE TABLE EBMD_KEYWORD
  (
    KEYWORDID    NUMBER(11,0) NOT NULL ENABLE,
    TENANTID     NUMBER(11,0) NOT NULL ENABLE,
    PARENTID     NUMBER(11,0),
    KEYWORD VARCHAR2(255 CHAR),
    CREATED      DATE,
    MODIFIED      DATE,
    DELETED      DATE,
    DELETIONFLAG NUMBER(1,0),
    CONSTRAINT CEBMF_K_PK PRIMARY KEY (KEYWORDID)  USING INDEX TABLESPACE DWH_ETL_INDEX ENABLE,
    CONSTRAINT CEBMF_K_FK_TN FOREIGN KEY (TENANTID) REFERENCES EBMD_TENANT(TENANTID)
  )
  TABLESPACE DWH_ETL_DATA ;
  
--  alter table   EBMD_KEYWORDGROUP add(   MODIFIED      DATE);
CREATE TABLE EBMD_KEYWORDGROUP
  (
    KEYWORDGROUPID NUMBER(11,0) NOT NULL ENABLE,
    TENANTID       NUMBER(11,0) NOT NULL ENABLE,
    PARENTID       NUMBER(11,0),
    KEYWORDGROUP VARCHAR2(255 CHAR),
    CREATED DATE,
        MODIFIED DATE,
    DELETED        DATE,
    DELETIONFLAG   NUMBER(1,0) ,
    CONSTRAINT CEBMD_KG_PK PRIMARY KEY (KEYWORDGROUPID)  USING INDEX TABLESPACE DWH_ETL_INDEX ENABLE,
    CONSTRAINT CEBMF_KG_FK_TN FOREIGN KEY (TENANTID) REFERENCES EBMD_TENANT(TENANTID)
  )
  TABLESPACE DWH_ETL_DATA ;


CREATE TABLE EBMD_AGENT
  (
    AGENTID            NUMBER(11,0),
    AGENTNAME          VARCHAR2(255 CHAR),
    AGENTLOGIN         VARCHAR2(255 CHAR),
    AGENTUSERID        VARCHAR2(255 CHAR),
    AGENTEMAIL         VARCHAR2(255 CHAR),
    AGENTROLEDESC      VARCHAR2(255 CHAR),
    AGENCYID           NUMBER(11,0),
    MONITORED          VARCHAR2(255 CHAR),
    MONITORINGDURATION NUMBER(11,0),
    EXTERNALFLAG       NUMBER(11),
    ACTIVE             NUMBER(1),
    PWEXPIRATIONON     DATE,
    ROUTINGMODELLIST   NUMBER(19,0), 
    CREATED DATE,
     MODIFIED            DATE,
    DELETED            DATE,
    DELETIONFLAG       NUMBER(1),
    CONSTRAINT CEBMD_A_PK PRIMARY KEY (AGENTID)  USING INDEX TABLESPACE DWH_ETL_INDEX ENABLE,
    CONSTRAINT CEBMD_A_FKAGENCY FOREIGN KEY (AGENCYID) REFERENCES EBMD_AGENCY(AGENCYID)
  )
  TABLESPACE DWH_ETL_DATA ;
CREATE TABLE EBMD_AGENCY_SLA
  (
    AGENCYID NUMBER(11,0),
    CHANNEL  VARCHAR2(25 CHAR),
    SLATIME  NUMBER(11,0),
    CONSTRAINT CEBMD_AG_SLA_PK PRIMARY KEY (AGENCYID,CHANNEL)  USING INDEX TABLESPACE DWH_ETL_INDEX ENABLE,
    CONSTRAINT CEBMD_AG_SLA_AFK FOREIGN KEY (AGENCYID) REFERENCES EBMD_AGENCY(AGENCYID)  ENABLE
  )
  TABLESPACE DWH_ETL_DATA ;
CREATE TABLE EBMF_EVENT_JN
  (
    LOGID           NUMBER(20,0) NOT NULL ENABLE,
    QUESTIONID      NUMBER(11,0) NOT NULL ENABLE,
    SUBPROJECTID    NUMBER,
    CREATED         DATE,
    MODIFIED        DATE,
    ASSIGN_AGENCYID NUMBER(11,0),
    EVENTSRC        CHAR(1 CHAR),
    EVENT           CHAR(2 CHAR),
    STATUS          VARCHAR2(100 CHAR),
    LOCKEDSINCE     DATE,
    LOCKEDBY        NUMBER(11,0),
    FOLLOWUPON      DATE,
    MXLASTACTIONON  DATE,
    DURATION        NUMBER,
    EXEC_AGENTID    NUMBER,
    EXEC_AGENCYID   NUMBER,
    RESPONSEID      NUMBER(11,0),
    CONSTRAINT CEBMF_EJN_PK PRIMARY KEY (LOGID) USING INDEX TABLESPACE DWH_ETL_INDEX ENABLE,
    CONSTRAINT CEBMF_EJN_FK_SP FOREIGN KEY (SUBPROJECTID) REFERENCES EBMD_SUBPROJECT(SUBPROJECTID) ,
    CONSTRAINT CEBMF_EJN_FK_AG FOREIGN KEY (ASSIGN_AGENCYID) REFERENCES EBMD_AGENCY(AGENCYID),
    CONSTRAINT CEBMF_EJN_FK_EV FOREIGN KEY (EVENT) REFERENCES EBMD_EVENT_DSC(EVENT),
    CONSTRAINT CEBMF_EJN_FK_LB FOREIGN KEY (LOCKEDBY) REFERENCES EBMD_AGENT(AGENTID) ,
    CONSTRAINT CEBMF_EJN_FK_AGT FOREIGN KEY (EXEC_AGENTID) REFERENCES EBMD_AGENT(AGENTID) ,
    CONSTRAINT CEBMF_EJN_FK_EA FOREIGN KEY (EXEC_AGENCYID) REFERENCES EBMD_AGENCY(AGENCYID)
  )
  TABLESPACE DWH_ETL_DATA ;
CREATE TABLE EBMF_QUESTIONMETA
  (
    TENANTID              NUMBER(11,0) NOT NULL ENABLE,
    QUESTIONID            NUMBER(11,0) NOT NULL ENABLE,
    CASEID                NUMBER(11,0),
    DOCID                 VARCHAR2(55 CHAR),
    SUBPROJECTID          NUMBER,
    CHANNEL               VARCHAR2(25 CHAR),
    QTYPE                 NUMBER(2,0),
    CUSTOMERID            VARCHAR2(10 CHAR),
    CONTRACTID            VARCHAR2(10 CHAR),
    CONTACTID             VARCHAR2(10 CHAR),
    LASTEVENT             CHAR(2 CHAR),
    CREATED               DATE,
    MODIFIED              DATE,
    FINISHED              DATE,
    FU_CREATED            DATE,
    FU_FINISHED           DATE,
    FIRSTCLOSING_AGENTID  NUMBER(11,0),
    FIRSTCLOSING_AGENCYID NUMBER(11,0),
    FIRSTCLOSING_DATE     DATE,
    EXEC_AGENTID          NUMBER(11,0),
    EXEC_AGENCYID         NUMBER(11,0),
    ASSIGN_AGENCYID       NUMBER(11,0),
    AG_CREATED            DATE,
    AG_FUTIME             NUMBER(20,0),
    AG_HANDLINGTIME       NUMBER(20,0),
    AG_IDLETIME           NUMBER(20,0),
    AG_TOTALTIME          NUMBER(20,0),
    AG_INSLA              NUMBER(1,0),
    AG_INSLAUNTIL         DATE,
    GLOBAL_HANDLINGTIME   NUMBER(20,0),
    GLOBAL_IDLETIME       NUMBER(20,0),
    GLOBAL_TOTALTIME      NUMBER(20,0),
    GLOBAL_FUTIME         NUMBER(20,0),
    GLOBAL_INSLA          NUMBER(1,0),
    GLOBAL_INSLAUNTIL     DATE,
    CONSTRAINT CEBMF_QUESTIONMETA_PK PRIMARY KEY (QUESTIONID) USING INDEX TABLESPACE DWH_ETL_INDEX ENABLE,
    CONSTRAINT CEBMF_QM_FK_EX_AGID FOREIGN KEY (EXEC_AGENCYID) REFERENCES EBMD_AGENCY(AGENCYID),
    CONSTRAINT CEBMF_QM_FK_EX_AGTID FOREIGN KEY (EXEC_AGENTID) REFERENCES EBMD_AGENT(AGENTID) ,
    CONSTRAINT CEBMF_QM_FK_AS_AGID FOREIGN KEY (ASSIGN_AGENCYID) REFERENCES EBMD_AGENCY(AGENCYID),
    CONSTRAINT CEBMF_QM_FK_FC_AGID FOREIGN KEY (FIRSTCLOSING_AGENCYID) REFERENCES EBMD_AGENCY(AGENCYID) ,
    CONSTRAINT CEBMF_QM_FK_FC_AGTID FOREIGN KEY (FIRSTCLOSING_AGENTID) REFERENCES EBMD_AGENT(AGENTID) ,
    CONSTRAINT CEBMF_QM_FK_TN FOREIGN KEY (TENANTID) REFERENCES EBMD_TENANT(TENANTID) ,
    CONSTRAINT CEBMF_QM_FK_SP FOREIGN KEY (SUBPROJECTID) REFERENCES EBMD_SUBPROJECT(SUBPROJECTID) ,
    CONSTRAINT CEBMF_QM_FK_CH FOREIGN KEY (CHANNEL) REFERENCES EBMD_CHANNEL(CHANNEL), 
    CONSTRAINT CEBMF_QM_FK_QT FOREIGN KEY (QTYPE) REFERENCES EBMD_QTYPE_DESC(QTYPE) 
    
  )
  TABLESPACE DWH_ETL_DATA ;
  
  CREATE TABLE EBMF_QUESTIONKEYWORD_JN
  (
    KEYWORDID    NUMBER(11,0) NOT NULL ENABLE,
    QUESTIONID   NUMBER(11,0) NOT NULL ENABLE,
    CREATED      DATE,
    DELETED      DATE,
    DELETIONFLAG NUMBER(1),
    CONSTRAINT CEBMF_QK_FK_KW FOREIGN KEY (KEYWORDID) REFERENCES EBMD_KEYWORD(KEYWORDID) ,
    CONSTRAINT CEBMF_QK_FK_Q FOREIGN KEY (QUESTIONID) REFERENCES EBMF_QUESTIONMETA(QUESTIONID)
  )
  TABLESPACE DWH_ETL_DATA ;

  
  
  
CREATE INDEX EBMF_EVENT_JN_IDX1 ON EBMF_EVENT_JN
  (
    CREATED,
    SUBPROJECTID,
    ASSIGN_AGENCYID,
    EVENT,
    QUESTIONID
  )
  TABLESPACE DWH_ETL_INDEX ;
CREATE INDEX EBMF_EVENT_JN_IDX2 ON EBMF_EVENT_JN
  (
    CREATED,
    SUBPROJECTID,
    EXEC_AGENCYID,
    EVENT,
    QUESTIONID
  )
  TABLESPACE DWH_ETL_INDEX ;
CREATE INDEX EBMF_EVENT_JN_IDX3 ON EBMF_EVENT_JN
  (
    CREATED,
    EVENT,
    EXEC_AGENCYID,
    SUBPROJECTID,
    QUESTIONID
  )
  TABLESPACE DWH_ETL_INDEX ;
CREATE INDEX EBMF_EVENT_JN_IDX4 ON EBMF_EVENT_JN
  (
    QUESTIONID,
    EVENT,
    ASSIGN_AGENCYID,
    SUBPROJECTID
  )
  TABLESPACE DWH_ETL_INDEX ;
CREATE INDEX EBMF_EVENT_JN_IDX5 ON EBMF_EVENT_JN
  (
    QUESTIONID,
    EVENT,
    CREATED,
    ASSIGN_AGENCYID,
    LOGID
  )
  TABLESPACE DWH_ETL_INDEX ;
CREATE INDEX EBMF_EVENT_JN_IDX6 ON EBMF_EVENT_JN
  (
    QUESTIONID,
    EVENT,
    RESPONSEID
  )
  TABLESPACE DWH_ETL_INDEX ;
CREATE INDEX EBMF_EVENT_JN_IDX7 ON EBMF_EVENT_JN
  (
    QUESTIONID,
    EVENT,
    LOGID
  )
  TABLESPACE DWH_ETL_INDEX ;
CREATE INDEX EBMF_QUESTIONMETA_IDX1 ON EBMF_QUESTIONMETA
  (
    TENANTID,
    QUESTIONID,
    CREATED,
    FINISHED
  )
  TABLESPACE DWH_ETL_INDEX ;
CREATE INDEX EBMF_QUESTIONMETA_IDX2 ON EBMF_QUESTIONMETA
  (
    TENANTID,
    DOCID,
    QUESTIONID
  )
  TABLESPACE DWH_ETL_INDEX ;
CREATE INDEX EBMF_QUESTIONMETA_IDX3 ON EBMF_QUESTIONMETA
  (
    TENANTID,
    CREATED,
    FINISHED
  )
  TABLESPACE DWH_ETL_INDEX ;
  
  
GRANT ALL ON EBM_CONFIG TO ITYX_MX;
GRANT ALL ON EBMD_EVENTGROUP_DSC TO ITYX_MX;
GRANT ALL ON EBMD_EVENT_DSC TO ITYX_MX;
GRANT ALL ON EBMD_QTYPE_DESC TO ITYX_MX;
GRANT ALL ON EBMD_CHANNEL TO ITYX_MX;
GRANT ALL ON EBMD_TENANT TO ITYX_MX;
GRANT ALL ON EBMD_SUBPROJECT TO ITYX_MX;
GRANT ALL ON EBMD_AGENCY TO ITYX_MX;
GRANT ALL ON EBMD_KEYWORD TO ITYX_MX;
GRANT ALL ON EBMD_KEYWORDGROUP TO ITYX_MX;
GRANT ALL ON EBMD_AGENT TO ITYX_MX;
GRANT ALL ON EBMD_AGENCY_SLA TO ITYX_MX;
GRANT ALL ON EBMF_EVENT_JN TO ITYX_MX;
GRANT ALL ON EBMF_QUESTIONMETA TO ITYX_MX;
GRANT ALL ON EBMF_QUESTIONKEYWORD_JN TO ITYX_MX;
  