//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.01.30 at 09:39:11 AM MEZ 
//


package com.nttdata.de.sky.archive;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}documentid"/>
 *         &lt;element ref="{}documentcount"/>
 *         &lt;element ref="{}datadictionary"/>
 *         &lt;element ref="{}archivecommand"/>
 *         &lt;element ref="{}readablesource"/>
 *         &lt;element ref="{}meta"/>
 *         &lt;element ref="{}IsCampaign"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "documentid",
    "documentcount",
    "datadictionary",
    "archivecommand",
    "readablesource",
    "meta",
    "isCampaign"
})
@XmlRootElement(name = "archive")
public class Archive {

    @XmlElement(required = true)
    protected String documentid;
    @XmlElement(required = true)
    protected BigInteger documentcount;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String datadictionary;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String archivecommand;
    @XmlElement(required = true)
    protected String readablesource;
    @XmlElement(required = true)
    protected Meta meta;
    @XmlElement(name = "IsCampaign", required = true)
    protected String isCampaign;

    /**
     * Gets the value of the documentid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentid() {
        return documentid;
    }

    /**
     * Sets the value of the documentid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentid(String value) {
        this.documentid = value;
    }

    /**
     * Gets the value of the documentcount property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDocumentcount() {
        return documentcount;
    }

    /**
     * Sets the value of the documentcount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDocumentcount(BigInteger value) {
        this.documentcount = value;
    }

    /**
     * Gets the value of the datadictionary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatadictionary() {
        return datadictionary;
    }

    /**
     * Sets the value of the datadictionary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatadictionary(String value) {
        this.datadictionary = value;
    }

    /**
     * Gets the value of the archivecommand property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArchivecommand() {
        return archivecommand;
    }

    /**
     * Sets the value of the archivecommand property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArchivecommand(String value) {
        this.archivecommand = value;
    }

    /**
     * Gets the value of the readablesource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadablesource() {
        return readablesource;
    }

    /**
     * Sets the value of the readablesource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadablesource(String value) {
        this.readablesource = value;
    }

    /**
     * Gets the value of the meta property.
     * 
     * @return
     *     possible object is
     *     {@link Meta }
     *     
     */
    public Meta getMeta() {
        return meta;
    }

    /**
     * Sets the value of the meta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Meta }
     *     
     */
    public void setMeta(Meta value) {
        this.meta = value;
    }

    /**
     * Gets the value of the isCampaign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsCampaign() {
        return isCampaign;
    }

    /**
     * Sets the value of the isCampaign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsCampaign(String value) {
        this.isCampaign = value;
    }

}
