package com.nttdata.de.sky.connector.siebel;

import com.nttdata.de.lib.logging.SkyLogger;

import javax.xml.ws.Endpoint;


/**
 * This class was generated by Apache CXF 2.4.3
 * 2012-01-10T14:37:21.095+01:00
 * Generated source version: 2.4.3
 */

public class PortType_SiebelServiceEndpoint_Server {

	protected PortType_SiebelServiceEndpoint_Server() throws java.lang.Exception {
		SkyLogger.getConnectorLogger().info("Starting Server");
		Object implementor = new MockupSblDynamicPortTypeImpl(null);
		String address = "http://localhost:13200/BusinessService/SiebelService";
		Endpoint.publish(address, implementor);
	}

	public static void main(String args[]) throws java.lang.Exception {
		new PortType_SiebelServiceEndpoint_Server();
		SkyLogger.getConnectorLogger().info("Server ready...");

		Thread.sleep(5 * 60 * 1000);
		SkyLogger.getConnectorLogger().info("Server exiting");
		System.exit(0);
	}
}
